name: Node.js CI

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      # secure: PoJ9o3UKTfrc74MabLmZRXnmqEHEa+uY2nbW2nUUrwE215jOaL2qmDnFSGytSXaqxU8hxPmnSbSo11lp7623Kfu4LfWiT+o4xTqLEXk9Mgqt1pjrrtLWAxOcswzOKCwDNeMmVhSIuBsrfoeOcMs0WuZ2mqcEnbF+TZhcfkB6mvk=
      # secure: OHKm2B9RoiJ+QpOx6tBbW4+HJbqkT9rk+kp/UisSXGqAeB0c6c5AEBOwmzRUIIKPhuZN7KauFo8HF/O33+079JxvuaXyc0LCF+4NSCvNxeIgmgxDou855VmvettCdnwRERAZxACwmXtoir3k6fZmfKI1dszhyknQPHKU6VtYcS8=
      # secure: Kap43AaU3Udp2ocxc3Ln5ztsWYlQJr/AlqoiXkozEZso/SMXbjlVmrf6YprZ6YfZgYXxrXZhRST9l/QJPu+uS1vc63iJSnPVYTI616eBVFKr6Yr30BXmJ9HJTrXA8B8mULj1gu+PtWC3memTM6r2TZynF6hxXHmbmbYoHDxswK8=
      # secure: flL/vngkUw3J6YvHgUg6gofazrgGCeM2hJnqgVm0KmGZO2FLpkFmtFy5MQiJVh/bC37YrKQ+RPyn8IOps+CZpTxAh3OBtEeJ24ynvGbnEZ12IpJp3U5w5nc7nUPCAstphgC2lCZtGEgGsGgoxBwsNHkdfJHCufqc0a0BdlXRhV8=

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 9

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/node_modules
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-yarn-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - run: yarn install --production=false
      - run: make eslint
      - run: make stylint
      - run: yarn test

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
